### ISSUE TITLE
Intelligibility detection algorithm is flaky

### ISSUE THREAD

**Issue by dthaler** [orcasound/orcanode-monitor#66]
PR #55 added an algorithm but it generates false Unintelligible signals multiple times a day

**Comment by scottveirs** [comment]
Does "Intelligibility" mean the audio data as a zero-amplitude signal, i.e. the data files are being created and uploaded but the hydrophone signal is absent in the time series?

If so, a possible short term solution would be to define a "no signal" status as a .ts segment where the standard deviation of the RMS amplitude is zero (not under some threshold). 

A longer-term solution would be to wait until shipnoise.net or a https://github.com/orcasound/orca-action-workflow deployed for all nodes is generating a recent time series of the sound pressure levels for short-term means, like by hour, minute, or second. Then use those time-series to detect zero standard deviation periods.

**Comment by dthaler** [comment]
Point Robinson isn't 0 amplitude, it seems to be a microphone hum with no actual signal but not just silence.  That makes it trickier to distinguish between a hum and normal steady state.

**Comment by dthaler** [comment]
Fixed by PR #137
